[versions]
kotlin = "1.9.21"
ksp = "1.9.21-1.0.15"
kotlinpoet = "1.15.1"
publishing = "0.25.3"
mockk = "1.13.8"
junit = "5.10.1"
compileTesting = "1.5.0"
binaryvalidator = "0.13.2"

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
# Compiled plugins
publishing-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publishing" }
# Test dependencies
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
compile-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "compileTesting" }
compile-testing-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "compileTesting" }

[bundles]
compile-testing = ["compile-testing", "compile-testing-ksp"]
kotlinpoet = ["kotlinpoet", "kotlinpoet-ksp"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
binaryvalidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryvalidator" }
