permissions:
  contents: write

name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create github release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Read version
      run: |
        version=$(cat trckr.version | tr -d '\n')
        echo "version=$version" >> $GITHUB_ENV

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}/changelog.md
        name: v${{ env.version }}
        tag_name: v${{ env.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
