name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  publish:
    name: Publish artifacts
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Publish artifacts to maven central
      run: ./gradlew publishAllPublicationsToMavenCentralRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USER }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASS }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASS }}

  publish-documentation:
    name: Publish documentation
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run dokka
      run: |
        ./gradlew dokkaHtmlMultiModule

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Build and upload docs
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
        pip3 install \
        mkdocs==1.5.3 \
        mkdocs-material==9.5.17 \
        mkdocs-material-extensions==1.3.1 \ 
        mkdocs-minify-plugin==0.8.0 \

        mkdocs build

        mkdocs gh-deploy --force

#  release:
#    name: Create github release
#    needs: [publish, publish-documentation]
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v4
#
#    - name: Read version
#      run: |
#        version=$(cat trckr.version | tr -d '\n')
#        echo "version=$version" >> $GITHUB_ENV
#
#    - name: Create release
#      uses: softprops/action-gh-release@v1
#      with:
#        body_path: ${{ github.workspace }}/changelog.md
#        name: v${{ env.version }}
#        tag_name: v${{ env.version }}
#        token: ${{ secrets.GITHUB_TOKEN }}
