name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run unit tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Check public API
      run: ./gradlew apiCheck

    - name: Run tests
      run: ./gradlew allTests
